### ISSUE TITLE
Support for x64

### ISSUE THREAD

**Issue by jsandv** [tkouba/OPCdotNET#2]
`
<PlatformTarget>x86</PlatformTarget>
`
What about X64?

**Comment by tkouba** [comment]
COM/DCOM must bitness be same as host process. Most OPC DA servers has x86, so you need to be x86 process.

**Comment by tkouba** [comment]
x64 is not planned. Maybe sometime in the future.

**Comment by duduyoyo** [comment]
This [solution](https://github.com/duduyoyo/WebSocket4OPC) supports x64 in C#, and most importantly there is no 3rd SDK or library required. Cheers!
